# Generated by Django 2.1.7 on 2019-02-16 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30, unique=True)),
                ('course_number', models.DecimalField(decimal_places=0, max_digits=3, unique=True)),
                ('credits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Course Start Date', verbose_name='Start Date')),
                ('end_date', models.DateField(help_text='Course Start Date', verbose_name='Start Date')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scms.Course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseInstanceTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('course_instance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scms.CourseInstance')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First Name', max_length=30)),
                ('last_name', models.CharField(help_text='Last Name', max_length=30)),
            ],
        ),
    ]
