# Generated by Django 2.1.7 on 2019-02-19 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseinstance',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='courseinstancetime',
            old_name='course_instance_id',
            new_name='course_instance',
        ),
    ]
